---
title: "Create LAS Script: for hte production of simple LAS files for testing r code"
author: "Mick Morrison"
date: "2025-06-29"
output:
  html:
    self-contained: TRUE
    theme: spacelab
editor: visual
---

```{r setup, include=FALSE}
# make rgl render to WebGL widgets rather than an on-screen device
options(rgl.useNULL = TRUE)
rgl::setupKnitr(autoprint = TRUE)  
```

## TEST-LAS Script

This script creates a synthetic LiDAR dataset with an assigned Coordinate Reference System (CRS) for development and testing purposes.()

```{r warning=FALSE}
library(lidR)
library(sf)
library(rgl)

## 1  generate synthetic cloud
set.seed(1)
n_pts <- 1000
df <- data.frame(
  X = runif(n_pts, 0, 100),
  Y = runif(n_pts, 0, 100),
  Z = runif(n_pts, 0, 30),
  Intensity       = sample(1:255, n_pts, TRUE),
  ReturnNumber    = 1L,
  NumberOfReturns = 1L,
  Classification  = 1L
)

## 2  build LAS & patch header
las <- LAS(df)
las@header@PHB$`File Source ID` <- 1L
las@header@PHB$`Version Major`  <- 1L
las@header@PHB$`Version Minor`  <- 2L
projection(las) <- 28356               # GDA94 / MGA 56

## 3  save & display (widget auto-prints)
writeLAS(las, "synth_las.las", index = TRUE)
plot3d(las$X, las$Y, las$Z, col = las$Intensity, size = 3)
rglwidget()
```
